apiVersion: v1
kind: Secret
metadata:
  name: rbd-cred
  namespace: kube-system
data:
#Please note this value is base64 encoded.
  adminID: YWRtaW4=
  adminSecret:  QVFBbXNHQmFwNEVvQmhBQUVUL0hjN2ZCcUFaai9jeTdjRGNvUUE9PQ==
  userID: a3ViZQ==
  userSecret: QVFBTWdYaFZ3QkNlRGhBQTlubFBhRnlmVVNhdEdENGRyRldEdlE9PQ==

