apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: rbd-csi-provisioner 
provisioner: csi-rbd
parameters:
   monitors: 172.24.0.6:6789
   pool: rbd
   adminID: admin
   adminSecret: AQAmsGBap4EoBhAAET/Hc7fBqAZj/cy7cDcoQA==
   userID: kube
   userSecret: AQAMgXhVwBCeDhAA9nlPaFyfUSatGD4drFWDvQ==
